{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keystone
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.service.publicService.name }}
            port:
              name: {{ .Values.service.publicService.portname }}
        path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
  - host: {{ .Values.ingress.hostname }}.{{ .Release.Namespace }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.service.publicService.name }}
            port:
              name: {{ .Values.service.publicService.portname }}
        path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
  - host: {{ .Values.ingress.hostname }}.{{ .Release.Namespace }}.svc.cluster.local
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.service.publicService.name }}
            port:
              name: {{ .Values.service.publicService.portname }}
        path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
{{- end }}
