{{- define "metadata.annotations.job.db_init" }}
{{- end }}

{{- $envAll := index . -}}
{{- $dbInitJob := dict "envAll" . "serviceName" "keystone" "dbUserPasswordName" "keystone-database-password" -}}
{{ $dbInitJob | include "common.manifests.job_db_init" }}
