{{- define "keystone.connInfo.podEnvVars" -}}
{{- $envAll := index . 0 -}}
env:
  - name: SECRET_ADMIN_KEY
    value: KEYSTONE_ADMIN_ENDPOINT
  - name: SECRET_ADMIN_VALUES
    value: {{ include "keystone.public.endpoints" $envAll | b64enc | quote }}
  - name: SECRET_INTERNAL_KEY
    value: KEYSTONE_INTERNAL_ENDPOINT
  - name: SECRET_INTERNAL_VALUES
    value: {{ include "keystone.internal.endpoints" $envAll | b64enc | quote }}
  - name: SECRET_PUBLIC_KEY
    value: KEYSTONE_PUBLIC_ENDPOINT
  - name: SECRET_PUBLIC_VALUES
    value: {{ include "keystone.public.endpoints" $envAll | b64enc | quote }}
{{- end -}}

{{- $envAll := index . -}}
{{- $podEnvVars := tuple . | include "keystone.connInfo.podEnvVars" | toString | fromYaml }}
{{- $connInfoSecretName := index $envAll.Values "openstack-dep" "connInfoSecret" }}
{{- $cmUpdateConnInfoJob := dict "envAll" . "serviceName" "keystone" "connInfoSecretName" $connInfoSecretName "podEnvVars" $podEnvVars.env -}}
{{ $cmUpdateConnInfoJob | include "common.manifests.job_update_conn_info" }}
