{{- define "metadata.annotations.job.cm_render" }}
{{- end }}

{{- define "keystone.render.podEnvVars" -}}
{{- $envAll := index . 0 -}}
env:
  - name: CONF_FILE_NAME
    value: keystone.conf
{{- end -}}

{{- $envAll := index . -}}
{{- $podEnvVars := tuple . | include "keystone.render.podEnvVars" | toString | fromYaml }}
{{- $cmRenderJob := dict "envAll" . "serviceName" "keystone" "dbUserPasswordName" "keystone-database-password" "podEnvVars" $podEnvVars.env "jobAnnotations" (include "metadata.annotations.job.cm_render" . | fromYaml) -}}
{{ $cmRenderJob | include "common.manifests.job_cm_render" }}
