{{- define "keystone.sync_db.volumeMounts" -}}
{{- $envAll := index . 0 -}}
volumeMounts:
  - name: keystone-etc
    mountPath: /var/lib/kolla/config_files/keystone.conf
    subPath: keystone.conf
{{- end }}

{{- $local := dict "podVolMounts" false -}}
{{- $_ := set $local "podVolMounts" ( index ( tuple . | include "keystone.sync_db.volumeMounts" | toString | fromYaml ) "volumeMounts" ) }}
{{- $dbSyncJob := dict "envAll" . "serviceName" "keystone" "podVolMounts" $local.podVolMounts -}}
{{ $dbSyncJob | include "common.manifests.job_db_sync" }}
