apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.endpoints.auth.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ $env := .Values.endpoints.auth.admin }}
  {{- $_ := set $env "os_internal_url"  (include "keystone.internal.endpoints" .) -}}
  {{- $_ := set $env "os_auth_url"  (include "keystone.public.endpoints" .) -}}
  OS_AUTH_URL: {{ .Values.endpoints.auth.admin.os_auth_url | b64enc | quote }}
  OS_INTERNAL_URL: {{ .Values.endpoints.auth.admin.os_internal_url | b64enc | quote }}
  OS_DEFAULT_DOMAIN: {{ .Values.endpoints.auth.admin.default_domain_id | b64enc | quote }}
  OS_PROJECT_DOMAIN_NAME: {{ .Values.endpoints.auth.admin.project_domain_name | b64enc | quote }}
  OS_PROJECT_NAME: {{ .Values.endpoints.auth.admin.project_name | b64enc | quote }}
  OS_REGION_NAME: {{ .Values.endpoints.auth.admin.region_name | b64enc | quote }}
  OS_USER_DOMAIN_NAME: {{ .Values.endpoints.auth.admin.user_domain_name | b64enc | quote }}
  OS_USERNAME: {{ .Values.endpoints.auth.admin.username | b64enc | quote }}
  OS_INTERFACE: {{ .Values.endpoints.auth.admin.interface | b64enc | quote }}
  OS_IDENTITY_API_VERSION: {{ .Values.endpoints.auth.admin.version | b64enc | quote }}
