chart-dirs:
  - charts
chart-repos:
  - kungze=https://kungze.github.io/charts
debug: true
helm-extra-args: --timeout 1000s
excluded-charts:
  - helm-toolkit
  - keystone
remote: origin
target-branch: main
