apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  cloud.conf: |-
    {{- if eq .Values.cloud.authStrategy "keystone" }}
    [Global]
    auth-strategy = keystone
    username = {{ .Values.cloud.username }}
    password = {{ .Values.cloud.password }}
    tenant-name = {{ .Values.cloud.tenantName }}
    auth-url = {{ .Values.cloud.authUrl }}
    os-endpoint-type = public
    domain-name = default
    region = RegionOne
    [BlockStorage]
    force-snapshot = true
    auth-strategy = keystone
    {{- else if eq .Values.cloud.authStrategy "noauth" }}
    [Global]
    auth-strategy = noauth
    [BlockStorage]
    force-snapshot = true
    auth-strategy = noauth
    {{- if not (empty .Values.cloud.cinderListenAddr )}}
    cinder-listen-addr = {{ .Values.cloud.cinderListenAddr }}
    {{- else}}
    cinder-listen-addr = http://{{ .Release.Name }}-noauth-cinder:8776/v3/
    {{- end }}
    {{- end }}
