apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{- range $key, $values := .Values.passwordEnvs }}
  {{ $key }}: {{ $values }}
  {{- end }}
