apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  {{ $password := .Values.passwordEnvs }}
  {{- range $key, $values := .Values.passwordEnvs }}
  {{- if not (empty $values) }}
    {{ $key }}: {{ $values | b64enc }}
  {{- else }}
  {{- $_ := set $password $key (randAlphaNum 10 | b64enc) -}}
  {{- if eq $key "rbd_secret_uuid" }}
  {{- $_ := set $password $key (uuidv4 | b64enc) }}
  {{- end }}
  {{- if eq $key "cinder_rbd_secret_uuid" }}
  {{- $_ := set $password $key (uuidv4 | b64enc) }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- range $key, $values := .Values.passwordEnvs }}
  {{ $key }}: {{ $values }}
  {{- end }}

