apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{- range $key, $values := .Values.passwordEnvs }}
  {{- if not (empty $values) }}
  {{ $key }}: {{ $values | b64enc | quote }}
  {{- else }}
  {{ $key }}: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
