---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ovs1
  labels:
    app: test-ovs1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ovs1
  template:
    metadata:
      labels:
        app: test-ovs1
    spec:
      hostNetwork: true
      containers:
        - name: openvswitch-vswitchd
          image: registry.aliyuncs.com/openstack-helm/ubuntu-source-openvswitch-vswitchd:master
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: "/var/lib/kolla/config_files/config.json"
              subPath: openvswitch-vswitchd.json
            - name: config
              mountPath: "/var/lib/kolla/config_files/start-ovs"
              subPath: start-ovs
            - name: run-openvswitch
              mountPath: "/run/openvswitch/"
            - name: lib-modules
              mountPath: "/lib/modules"
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: "COPY_ALWAYS"
            - name: KOLLA_SERVICE_NAME
              value: "openvswitch-vswitchd"
            - name: PATH
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            - name: LANG
              value: "en_US.UTF-8"
            - name: KOLLA_BASE_DISTRO
              value: "ubuntu"
            - name: KOLLA_DISTRO_PYTHON_VERSION
              value: "3.8"
            - name: KOLLA_BASE_ARCH
              value: "x86_64"
            - name: SETUPTOOLS_USE_DISTUTILS
              value: "stdlib"
            - name: PS1
              value: "$(tput bold)($(printenv KOLLA_SERVICE_NAME))$(tput sgr0)[$(id -un)@$(hostname -s) $(pwd)]$ "
            - name: DEBIAN_FRONTEND
              value: "noninteractive"
        - name: openvswitch-db
          image: registry.aliyuncs.com/openstack-helm/ubuntu-source-openvswitch-db-server:master
          volumeMounts:
            - name: config
              mountPath: "/var/lib/kolla/config_files/config.json"
              subPath: openvswitch-db-server.json
            - name: config
              mountPath: "/var/lib/kolla/config_files/start-ovsdb-server"
              subPath: start-ovsdb-server
            - name: run-openvswitch
              mountPath: "/run/openvswitch/"
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: "COPY_ALWAYS"
            - name: KOLLA_SERVICE_NAME
              value: "openvswitch-db"
            - name: PATH
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            - name: LANG
              value: "en_US.UTF-8"
            - name: KOLLA_BASE_DISTRO
              value: "ubuntu"
            - name: KOLLA_DISTRO_PYTHON_VERSION
              value: "3.8"
            - name: KOLLA_BASE_ARCH
              value: "x86_64"
            - name: SETUPTOOLS_USE_DISTUTILS
              value: "stdlib"
            - name: PS1
              value: "$(tput bold)($(printenv KOLLA_SERVICE_NAME))$(tput sgr0)[$(id -un)@$(hostname -s) $(pwd)]$ "
            - name: DEBIAN_FRONTEND
              value: "noninteractive"
        - name: ovn-controller
          image: registry.aliyuncs.com/openstack-helm/ubuntu-source-ovn-controller:master
          volumeMounts:
            - name: config
              mountPath: "/var/lib/kolla/config_files/config.json"
              subPath: ovn-controller.json
            - name: run-openvswitch
              mountPath: "/run/openvswitch/"
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: "COPY_ALWAYS"
            - name: KOLLA_SERVICE_NAME
              value: "ovn-controller"
            - name: PATH
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            - name: LANG
              value: "en_US.UTF-8"
            - name: KOLLA_BASE_DISTRO
              value: "ubuntu"
            - name: KOLLA_DISTRO_PYTHON_VERSION
              value: "3.8"
            - name: KOLLA_BASE_ARCH
              value: "x86_64"
            - name: SETUPTOOLS_USE_DISTUTILS
              value: "stdlib"
            - name: PS1
              value: "$(tput bold)($(printenv KOLLA_SERVICE_NAME))$(tput sgr0)[$(id -un)@$(hostname -s) $(pwd)]$ "
            - name: DEBIAN_FRONTEND
              value: "noninteractive"
        - name: kolla-toolbox
          image: registry.aliyuncs.com/openstack-helm/ubuntu-source-kolla-toolbox:master
          securityContext:
            privileged: true
          lifecycle:
            postStart:
              exec:
                command: 
                  - "sh"
                  - "-c"
                  - >
                    tunnel_interface_address=$POD_IP;
                    system_id=$POD_NAME;
                    sudo /opt/ansible/bin/ansible localhost -m openvswitch_db -a "table=Open_vSwitch record=. col=external_ids key=system-id value=$system_id state=present";
                    sudo /opt/ansible/bin/ansible localhost -m openvswitch_bridge -a "bridge='br-int' state='present' fail_mode='secure'";
                    sudo /opt/ansible/bin/ansible localhost -m openvswitch_db -a "table=Open_vSwitch record=. col=external_ids key=ovn-encap-ip value=$tunnel_interface_address state=present";
                    sudo /opt/ansible/bin/ansible localhost -m openvswitch_db -a "table=Open_vSwitch record=. col=external_ids key=ovn-encap-type value=geneve state=present";
                    sudo /opt/ansible/bin/ansible localhost -m openvswitch_db -a "table=Open_vSwitch record=. col=external_ids key=ovn-remote value=tcp:test-ovn1.default.svc.cluster.local:6642 state=present";
                    sudo /opt/ansible/bin/ansible localhost -m openvswitch_db -a "table=Open_vSwitch record=. col=external_ids key=ovn-remote-probe-interval value=60000 state=present";
                    sudo /opt/ansible/bin/ansible localhost -m openvswitch_db -a "table=Open_vSwitch record=. col=external_ids key=ovn-cms-options value=60000 state=present";
          volumeMounts:
            - name: config
              mountPath: "/var/lib/kolla/config_files/config.json"
              subPath: kolla-toolbox.json
            - name: config
              mountPath: "/etc/sudoers.d/kolla_ansible_sudoers"
              subPath: kolla-toolbox-sudoer
            - name: run-openvswitch
              mountPath: "/run/openvswitch/"
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: "COPY_ALWAYS"
            - name: ANSIBLE_LIBRARY
              value: /usr/share/ansible
            - name: KOLLA_SERVICE_NAME
              value: "kolla-toolbox"
            - name: PATH
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            - name: LANG
              value: "en_US.UTF-8"
            - name: KOLLA_BASE_DISTRO
              value: "ubuntu"
            - name: KOLLA_DISTRO_PYTHON_VERSION
              value: "3.8"
            - name: KOLLA_BASE_ARCH
              value: "x86_64"
            - name: SETUPTOOLS_USE_DISTUTILS
              value: "stdlib"
            - name: PS1
              value: "$(tput bold)($(printenv KOLLA_SERVICE_NAME))$(tput sgr0)[$(id -un)@$(hostname -s) $(pwd)]$ "
            - name: DEBIAN_FRONTEND
              value: "noninteractive"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: config
          configMap:
            name: ovn-conf
        - name: run-openvswitch
          emptyDir: {}
        - name: lib-modules
          hostPath:
            path: /lib/modules
            type: Directory
