apiVersion: v1
kind: ServiceAccount
metadata:
  name: cinder-api
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cinder-api
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - extensions
  - batch
  - apps
  resources:
  - services
  - endpoints
  - jobs
  - pods
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cinder-api
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cinder-api
subjects:
- kind: ServiceAccount
  name: cinder-api
  namespace: {{ .Release.Namespace | quote }}
