apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.connInfoSecret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
type: Opaque
data:
  {{ $env := .Values.openstackEnv }}
  {{- $_ := set $env "rabbitmqUrl"  (include "rabbitmq.connInfo" .) -}}
  {{- $_ := set $env "mariadbUrl" (include "mariadb.connInfo" .) -}}
  {{- $_ := set $env "memcacheUrl" (include "memcached.connInfo" .) -}}
  RABBITMQ_URL: {{ .Values.openstackEnv.rabbitmqUrl | b64enc }}
  MEMCACHE_URL: {{ .Values.openstackEnv.memcacheUrl | b64enc }}
  MARIADB_URL: {{ .Values.openstackEnv.mariadbUrl | b64enc }}
