apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.connInfoSecret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  RABBITMQ_URL: {{ .Values.openstackEnv.rabbitmqUrl | b64enc }}
  DATABASE_URL: {{ .Values.openstackEnv.databaseUrl | b64enc }}
  DATABASE_HOST: {{ .Values.openstackEnv.databaseHost | b64enc }}
  MEMCACHE_URL: {{ .Values.openstackEnv.memcacheUrl | b64enc }}
