apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.connInfoSecret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
type: Opaque
data:
  {{ $env := .Values.openstackEnv }}
  {{- $_ := set $env "rabbitmqUrl"  (include "rabbitmq.connInfo" .) -}}
  {{- $_ := set $env "databaseUrl" (include "database.connInfo" .) -}}
  {{- $_ := set $env "databaseHost" (include "openstack.databaseHost" .) -}}
  {{- $_ := set $env "memcacheUrl" (include "memcached.connInfo" .) -}}
  RABBITMQ_URL: {{ .Values.openstackEnv.rabbitmqUrl | b64enc }}
  DATABASE_URL: {{ .Values.openstackEnv.databaseUrl | b64enc }}
  DATABASE_HOST: {{ .Values.openstackEnv.databaseHost | b64enc }}
  MEMCACHE_URL: {{ .Values.openstackEnv.memcacheUrl | b64enc }}
