apiVersion: v1
kind: Secret
metadata:
  name: temp-set-conn-info
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
type: Opaque
data:
  {{ $env := .Values.openstackEnv }}
  {{- $_ := set $env "rabbitmqUrl"  (include "rabbitmq.connInfo" .) -}}
  {{- $_ := set $env "databaseUrl" (include "database.connInfo" .) -}}
  {{- $_ := set $env "databaseHost" (include "openstack.databaseHost" .) -}}
  {{- $_ := set $env "memcacheUrl" (include "memcached.connInfo" .) -}}
