## @section 自动生成openstack dependency 相关密码

## openstack gen password secret name
## @param secretName [t#secret 名称] 生成openstack相关密码的secret名称
secretName: openstack-password
## Generate openstack dependency password
## @param passwordEnvs.mariadb-root-password [t#root 密码] 数据库 root 用户密码
## @param passwordEnvs.keystone-database-password [t#Keystone 数据库密码] Keystone 数据库密码
## @param passwordEnvs.keystone-admin-password [t#Keystone admin 用户密码] Keystone admin 用户密码
## @param passwordEnvs.glance-database-password [t#Glance 数据库密码] Glance 数据库密码
## @param passwordEnvs.glance-keystone-password [t#Glance 用户密码] Glance 用户密码
## @param passwordEnvs.cinder-database-password [t#Cinder 数据库密码] Cinder 数据库密码
## @param passwordEnvs.cinder-keystone-password [t#Cinder 用户密码] Cinder 用户密码
## @param passwordEnvs.neutron-database-password [t#Neutron 数据库密码] Neutron 数据库密码
## @param passwordEnvs.neutron-keystone-password [t#Neutron 用户密码] Neutron 用户密码
## @param passwordEnvs.nova-database-password [t#Nova 数据库密码] Nova 数据库密码
## @param passwordEnvs.nova-keystone-password [t#Nova 用户密码] Nova 用户密码
## @param passwordEnvs.placement-database-password [t#Placement 数据库密码] Placement 数据库密码
## @param passwordEnvs.placement-keystone-password [t#Placement 用户密码] Placement 用户密码
## @param passwordEnvs.rabbitmq-password [t#Rabbitmq 用户密码] Rabbitmq 用户密码
## @param passwordEnvs.rbd_secret_uuid [t#rbd secret uuid] rbd_secret_uuid is only used for nova
## @param passwordEnvs.cinder_rbd_secret_uuid [t#cinder rbd secret uuid] cinder_rbd_secret_uuid is used for cinder
passwordEnvs:
  mariadb-root-password: ""
  keystone-admin-password: ""
  keystone-database-password: ""
  glance-database-password: ""
  glance-keystone-password: ""
  cinder-database-password: ""
  cinder-keystone-password: ""
  neutron-keystone-password: ""
  neutron-database-password: ""
  nova-database-password: ""
  nova-keystone-password: ""
  placement-database-password: ""
  placement-keystone-password: ""
  rabbitmq-password: ""
  rbd_secret_uuid: ""
  cinder_rbd_secret_uuid: ""
