{{- if .Values.conf.ceph.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.conf.ceph.ceph_secret_name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.conf.ceph.ceph_cm_name }}
  namespace: {{ .Release.Namespace }}
data:
{{- end }}
