{{- define "metadata.annotations.job.db_sync" }}
{{- end }}

{{- define "cinder.sync_db.volumeMounts" -}}
{{- $envAll := index . 0 -}}
volumeMounts:
  - name: cinder-etc
    mountPath: /var/lib/kolla/config_files/cinder.conf
    subPath: cinder.conf
{{- end }}

{{- $local := dict "podVolMounts" false -}}
{{- $_ := set $local "podVolMounts" ( index ( tuple . | include "cinder.sync_db.volumeMounts" | toString | fromYaml ) "volumeMounts" ) }}
{{- $dbSyncJob := dict "envAll" . "serviceName" "cinder" "podVolMounts" $local.podVolMounts "jobAnnotations" (include "metadata.annotations.job.db_sync" . | fromYaml) -}}
{{ $dbSyncJob | include "common.manifests.job_db_sync" }}
