apiVersion: batch/v1
kind: Job
metadata:
  name: cinder-type-create
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: cinder-bootstrap
          image: {{ template "kolla.toolbox.image" . }}
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - /tmp/volume-type-create.sh
          env:
            - name: OS_USERNAME
              valueFrom:
                secretKeyRef:
                  key: OS_USERNAME
                  name: {{ .Values.endpoints.auth.secretName }}
            - name: OS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: keystone-admin-password
                  name: {{ index .Values "openstack-dep" "passwordSecretName" }}
            - name: OS_AUTH_URL
              valueFrom:
                secretKeyRef:
                  key: OS_INTERNAL_URL
                  name: {{ .Values.endpoints.auth.secretName }}
            - name: OS_INTERFACE
              valueFrom:
                secretKeyRef:
                  key: OS_INTERFACE
                  name: {{ .Values.endpoints.auth.secretName }}
            - name: OS_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  key: OS_PROJECT_DOMAIN_NAME
                  name: {{ .Values.endpoints.auth.secretName }}
            - name: OS_REGION_NAME
              valueFrom:
                secretKeyRef:
                  key: OS_REGION_NAME
                  name: {{ .Values.endpoints.auth.secretName }}
            - name: OS_IDENTITY_API_VERSION
              valueFrom:
                secretKeyRef:
                  key: OS_IDENTITY_API_VERSION
                  name: {{ .Values.endpoints.auth.secretName }}
            - name: OS_PROJECT_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  key: OS_PROJECT_DOMAIN_NAME
                  name: {{ .Values.endpoints.auth.secretName }}
            - name: OS_USER_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  key: OS_USER_DOMAIN_NAME
                  name: {{ .Values.endpoints.auth.secretName }}
            - name: OS_PROJECT_NAME
              valueFrom:
                secretKeyRef:
                  key: OS_PROJECT_NAME
                  name: {{ .Values.endpoints.auth.secretName }}
          volumeMounts:
          - mountPath: /tmp
            name: pod-tmp
          - mountPath: /tmp/volume-type-create.sh
            name: cinder-bin
            subPath: volume-type-create.sh
      initContainers:
        - name: init
          image: {{ template "entrypoint.image" . }}
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          command:
            - kubernetes-entrypoint
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: {{ .Release.Namespace }}:{{ include "common.utils.joinListWithComma" .Values.dependencies.type_create.service }}
      restartPolicy: OnFailure
      serviceAccount: {{ .Values.serviceAccountName}}
      serviceAccountName: {{ .Values.serviceAccountName}}
      volumes:
        - emptyDir: {}
          name: pod-tmp
        - name: cinder-bin
          configMap:
            defaultMode: 0755
            name: cinder-bin
