apiVersion: v1
data:
  ml2_conf.ini: "# ml2_conf.ini\n[ml2]\n# Changing type_drivers after bootstrap can
    lead to database inconsistencies\ntype_drivers = flat,vlan\ntenant_network_types
    = vlan\nmechanism_drivers = linuxbridge\nextension_drivers = port_security\n\n[ml2_type_vlan]\nnetwork_vlan_ranges
    = physnet1\n\n[ml2_type_flat]\nflat_networks = *\n \n"
  neutron-server.json: |
    {
        "command": "neutron-server --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini",
        "config_files": [
            {
                "source": "/var/lib/kolla/config_files/neutron.conf",
                "dest": "/etc/neutron/neutron.conf",
                "owner": "neutron",
                "perm": "0600"
            },
            {
                "source": "/var/lib/kolla/config_files/ml2_conf.ini",
                "dest": "/etc/neutron/plugins/ml2/ml2_conf.ini",
                "owner": "neutron",
                "perm": "0600"
            }
        ],
        "permissions": [
            {
                "path": "/var/log/kolla/neutron",
                "owner": "neutron:neutron",
                "recurse": true
            }
        ]
    }
  neutron-sudoer: |
    neutron ALL=(ALL) NOPASSWD: ALL
  neutron.conf: "# neutron.conf\n[DEFAULT]\ndebug = false\n\n#
    NOTE(elemoine): set use_stderr to False or the logs will also be sent to\n# stderr
    and collected by Docker\nuse_stderr = False\nbind_host = 0.0.0.0\n\nbind_port
    = 9696\n\napi_paste_config = /etc/neutron/api-paste.ini\n\napi_workers = 1\nmetadata_workers
    = 1\nrpc_workers = 1\nrpc_state_report_workers = 1\n\n# NOTE(SamYaple): We must
    specify this value here rather than the metadata conf\n# because it is used by
    the l3 and dhcp agents. The reason the path has 'kolla'\n# in it is because we
    are sharing this socket in a volume which is it's own dir\nmetadata_proxy_socket
    = /var/lib/neutron/kolla/metadata_proxy\n\ninterface_driver = linuxbridge\n\nallow_overlapping_ips
    = true\n\ncore_plugin = ml2\nservice_plugins = router\n\ntransport_url = rpc_transport_url\n\nauth_strategy
    = noauth\n\n[oslo_concurrency]\nlock_path = /var/lib/neutron/tmp\n\n[agent]\nroot_helper
    = sudo neutron-rootwrap /etc/neutron/rootwrap.conf\n\n[database]\nconnection =
    mysql+pymysql://neutron:database_password_placeholder@database_address_placeholder/neutron\nmax_retries
    = -1\n\n\n[privsep]\nhelper_command=sudo neutron-rootwrap /etc/neutron/rootwrap.conf
    privsep-helper\n \n"
  linuxbridge_agent.ini:  |
    [agent]
    
    [linux_bridge]
    physical_interface_mappings = physnet1:ens10
    
    [securitygroup]
    firewall_driver = neutron.agent.linux.iptables_firewall.IptablesFirewallDriver

    [vxlan]
    enable_vxlan = False
  neutron-linuxbridge-agent.json: |
    {
        "command": "neutron-linuxbridge-agent --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/linuxbridge_agent.ini",
        "config_files": [
            {   
                "source": "/var/lib/kolla/config_files/neutron.conf",
                "dest": "/etc/neutron/neutron.conf",
                "owner": "neutron",
                "perm": "0600"
            },  
                    {   
                "source": "/var/lib/kolla/config_files/linuxbridge_agent.ini",
                "dest": "/etc/neutron/plugins/ml2/linuxbridge_agent.ini",
                "owner": "neutron",
                "perm": "0600"
            }   
        ],  
        "permissions": [
            {   
                "path": "/var/log/kolla/neutron",
                "owner": "neutron:neutron",
                "recurse": true
            }   
        ]   
    }
  dhcp_agent.ini: |
    [DEFAULT]
    dnsmasq_config_file = /etc/neutron/dnsmasq.conf
    enable_isolated_metadata = true
    force_metadata = true
    dnsmasq_dns_servers = 1.1.1.1,8.8.8.8,8.8.4.4
  dnsmasq.conf: |
    log-async
    log-facility=/var/log/kolla/neutron/dnsmasq.log
  neutron-dhcp-agent.json: |
    {
        "command": "neutron-dhcp-agent --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/dhcp_agent.ini",
        "config_files": [
            {
                "source": "/var/lib/kolla/config_files/neutron.conf",
                "dest": "/etc/neutron/neutron.conf",
                "owner": "neutron",
                "perm": "0600"
            },
            {
                "source": "/var/lib/kolla/config_files/dhcp_agent.ini",
                "dest": "/etc/neutron/dhcp_agent.ini",
                "owner": "neutron",
                "perm": "0600"
            },
            {
                "source": "/var/lib/kolla/config_files/dnsmasq.conf",
                "dest": "/etc/neutron/dnsmasq.conf",
                "owner": "neutron",
                "perm": "0600"
            }    ],
        "permissions": [
            {
                "path": "/var/log/kolla/neutron",
                "owner": "neutron:neutron",
                "recurse": true
            },
            {
                "path": "/var/lib/neutron/kolla",
                "owner": "neutron:neutron",
                "recurse": true
            }
        ]
    }
kind: ConfigMap
metadata:
  name: neutron-conf
